version: "3.8"

services:
  fake-smtp:
    image: munkyboy/fakesmtp
    container_name: fake-smtp
    ports:
      - "25:25"
    volumes:
      - ~/fake-smtp-emails:/var/mail
    depends_on:
      - keycloak
  fake-smtp-web:
    image: mjstewart/fakesmtp-web:1.3
    container_name: fake-smtp-web
    ports:
      - "60500:8080"
    volumes:
      - ~/fake-smtp-emails:/var/mail
    environment:
      - EMAIL_INPUT_DIR_POLL_RATE_SECONDS=10
    depends_on:
      - fake-smtp
  mysql:
    image: mysql:5.7.38
    container_name: mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"

  db-accounts:
    image: mysql:8.0.32
    container_name: db-accounts
    command: --default-authentication-plugin=mysql_native_password
    environment:
      - MYSQL_DATABASE=db_accounts
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_USER=accounts
      - MYSQL_PASSWORD=password
    ports:
      - "3308:3306"

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL_HOST=mysql
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
    ports:
      - "8080:8080"
    command: start-dev
    depends_on:
      - mysql
    healthcheck:
      test: "curl -f http://localhost:8080/admin || exit 1"

  ms-discovery:
    build: ms-discovery
    container_name: ms-discovery
    restart: always
    depends_on:
      - mysql
    ports:
      - "8761:8761"

  ms-config-server:
    build: ms-config-server
    container_name: ms-config-server
    restart: always
    depends_on:
      - ms-discovery
    ports:
      - "8888:8888"

  ms-gateway:
    build: ms-gateway
    container_name: ms-gateway
    restart: always
    depends_on:
      - ms-config-server
    ports:
      - "8090:8090"
    env_file:
      - ./ms-gateway/.env

  ms-users:
    build: ms-users
    container_name: ms-users
    restart: always
    depends_on:
      - ms-gateway
    ports:
      - "8084:8084"
    env_file:
      - ./ms-users/.env

  ms-accounts:
    build: ms-accounts
    container_name: ms-accounts
    restart: always
    depends_on:
      - db-accounts
      - ms-users
    ports:
      - "8085:8085"
    env_file:
      - ./ms-accounts/.env

  phpmyadmin-db-accounts:
    image: phpmyadmin/phpmyadmin:4.8.5
    restart: always
    depends_on:
      - db-accounts
    environment:
      - PMA_HOST=db-accounts
      - PMA_PORT=3306
      - PMA_USER=accounts
      - PMA_PASSWORD=password
    ports:
      - "3001:80"