version: "3.8"

services:

  mysql:
    image: mysql:5.7.38
    container_name: mysql
    ports:
      - "3307:3307"
    environment:
      - MYSQL_DATABASE=keycloak
      - MYSQL_USER=keycloak
      - MYSQL_PASSWORD=password
      - MYSQL_ROOT_PASSWORD=root_password
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"

  dbAccounts:
    image: mysql:latest
    container_name: dbAccounts
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "3308:3306"
    environment:
      - MYSQL_DATABASE=dbaccounts
      - MYSQL_USER=msaccount
      - MYSQL_PASSWORD=root
      - MYSQL_ROOT_PASSWORD=root
    healthcheck:
      test: "mysqladmin ping -u root -p$${MYSQL_ROOT_PASSWORD}"

  keycloak:
    image: quay.io/keycloak/keycloak:18.0.0
    container_name: keycloak
    environment:
      - KEYCLOAK_ADMIN=admin
      - KEYCLOAK_ADMIN_PASSWORD=admin
      - KC_DB=mysql
      - KC_DB_URL_HOST=mysql
      - KC_DB_URL_DATABASE=keycloak
      - KC_DB_USERNAME=keycloak
      - KC_DB_PASSWORD=password
    ports:
      - "8080:8080"
    command: start-dev
    depends_on:
      - mysql
    healthcheck:
      test: "curl -f http://localhost:8080/admin || exit 1"

  ms-discovery:
    build: ms-discovery
    container_name: ms-discovery
    restart: always
    depends_on:
      - mysql
    ports:
      - "8761:8761"

  ms-config-server:
    build: ms-config-server
    container_name: ms-config-server
    restart: always
    depends_on:
      - ms-discovery
    ports:
      - "8888:8888"

  ms-gateway:
    build: ms-gateway
    container_name: ms-gateway
    restart: always
    depends_on:
      - ms-config-server
    ports:
      - "8090:8090"
    environment:
      - KCK_GATEWAY_CLIENT_SECRET=2EsaCfgAhbQQrB45LyGHmyw9R3U1M7Uu
      - MS_GATEWAY_PROFILE=dev
      - CONFIG_SERVER_HOST=ms-config-server

  ms-users:
    build: ms-users
    container_name: ms-users
    restart: always
    depends_on:
      - ms-gateway
    ports:
      - "8084:8084"
    environment:
      - KCK_USERS_CLIENT_SECRET=0MF1GiXEtO6pn2Ky5UX4qUlZkwmxZVtX
      - MS_USERS_PROFILE=dev
      - CONFIG_SERVER_HOST=ms-config-server

  ms-accounts:
    build: ms-accounts
    container_name: ms-accounts
    restart: always
    depends_on:
      - dbAccounts
      - ms-users
    ports:
      - "8085:8085"
    environment:
      - KCK_ACCOUNTS_CLIENT_SECRET=jqFQcdM5dKOXvcPeJk2xmfEavnhZHyP3
      - MS_ACCOUNTS_PROFILE=dev
      - CONFIG_SERVER_HOST=ms-config-server
