server:
  port: ${PORT_MS_ACCOUNT:8085}

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: ms-account
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: ${MS_ACCOUNT_PROFILE:dev}
