server:
  port:  ${PORT_MS_GATEWAY:8090}

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: ms-gateway
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: ${MS_GATEWEAY_PROFILE:dev}
    gateway:
      default-filters:
        - TokenRelay
      routes:
        - id: ms-users
          uri: lb://MS-USERS:8084
          predicates:
            - Path=/users/**
          #        - id: ms-bill
          #          uri: lb://MS-BILLS:9191
          #          predicates:
          #            - Path=/bills/**
          filters:
            - StripPrefix=2
  security:
    oauth2:
      client:
        provider:
          keycloak-provider:
            issuer-uri: http://localhost:8080/realms/dmhRealm
        registration:
          keycloak-spring-gateway-client:
            provider: keycloak-provider
            scope: openid
            client-id: ms-gateway-client
            client-secret: ${KCK_GATEWAY_CLIENT_SECRET:qI6eIic7tR2xho7jYOqGEd4wZ29TL61e}
            authorization-grant-type: authorization_code
            redirect-uri: "{baseUrl}/login/oauth2/code/keycloak"

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

info:
  name: Servico de roteamento (API Gateway) para os demais servicos presentes no ecossistema da aplicacao.
  author: Grupo 03
  severity: Alto

logging:
  level:
    org.springframework.security: DEBUG
  pattern:
    dateformat: 'dd-MM-yyyy HH:mm:ss.SSS'
    console: '%clr(%d{"dd-MM-yyyy''T''HH:mm:ss"}){faint} %highlight(%clr(${LOG_LEVEL_PATTERN:-%5p})) %clr(${PID:- })
    %clr(---){faint} %clr([%15.15t]){faint} %clr([%-40.40logger{39}]:%line){cyan} %clr(-){faint} %m%n%wEx'