server:
  port: ${PORT_MS_USERS:8084}

eureka:
  instance:
    hostname: ms-discovery
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: ms-users
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: ${MS_USERS_PROFILE:dev}
