server:
  port: ${PORT_MS_USERS:8084}

eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka

spring:
  application:
    name: ms-users
  config:
    import: optional:configserver:http://localhost:8888
  cloud:
    config:
      profile: ${MS_GATEWEAY_PROFILE:dev}
  security:
    oauth2:
      client:
        registration:
          keycloak:
            provider: keycloak-provider
            client-id: ms-users-client
            scope: openid
            authorization-grant-type: client_credentials
            client-secret: ${KCK_USER_CLIENT_SECRET:4VkJb1ZOgAMItGEDDhtRFPi89TzFU7cL}
        provider:
          keycloak-provider:
            token-uri: http://localhost:8080/realms/dmhRealm/protocol/openid-connect/token
      resource-server:
        jwt:
          issuer-uri: http://localhost:8080/realms/dmhRealm/protocol/openid-connect/certs

dmh:
  keycloak:
    server-url: http://localhost:8080/
    realm: dmhRealm
    client-id: ms-users-client
    client-secret: ${KCK_USER_CLIENT_SECRET:4VkJb1ZOgAMItGEDDhtRFPi89TzFU7cL}

management:
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: health,info

info:
  name: Servico de usuários.
  author: Grupo 03
  severity: Alto

logging:
  level:
    org.springframework.security: DEBUG
  pattern:
    dateformat: 'dd-MM-yyyy HH:mm:ss.SSS'
    console: '%clr(%d{"dd-MM-yyyy''T''HH:mm:ss"}){faint} %highlight(%clr(${LOG_LEVEL_PATTERN:-%5p})) %clr(${PID:- })
    %clr(---){faint} %clr([%15.15t]){faint} %clr([%-40.40logger{39}]:%line){cyan} %clr(-){faint} %m%n%wEx'